GET http://localhost:4000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsImlhdCI6MTY5NTAwNjY5MywiZXhwIjoxNjk1MDA2NzAzfQ.XghLoUnEPNHDkhaS9ywhwIp9yGwaMEThMOvUgWBPwVg

###
POST http://localhost:4000/refresh-token
Content-Type: application/json

{
    "REFRESH_TOKEN":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEsImlhdCI6MTY5NTAwNjQzOH0.1xFHwgCD01ScHpbZIT_hsTx-SUjZIxRztZz_YAzyzyk"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"Buboy",
    "password":"JEWEL"
}

